### ISSUE TITLE
Hard to see social icons

### ISSUE THREAD

**Issue by zomeru** [SnoopyCodeX/portfolio#1]
Social icons are very hard to see on your contact section.

![issue](https://user-images.githubusercontent.com/19688908/130036751-1d57890c-c234-496c-82eb-fb8ecd5f0192.jpg)

**Comment by SnoopyCodeX** [comment]
> Social icons are very hard to see on your contact section.
> 
> ![issue](https://user-images.githubusercontent.com/19688908/130036751-1d57890c-c234-496c-82eb-fb8ecd5f0192.jpg)

Thank you for your suggestion ❤️ , I will be updating my portfolio after I've finished my other tasks.
